Adapt tests to changes when choosing reporting library

diff --git a/tests/integration/reportinglib/1.check.in b/tests/integration/reportinglib/1.check.in
--- a/tests/integration/reportinglib/1.check.in
+++ b/tests/integration/reportinglib/1.check.in
@@ -4,22 +4,45 @@
 
 OK=0
 FAILED=1
+sonata_reports=@ENABLE_SONATA_REPORTS@
+reportinglib=@ENABLE_REPORTINGLIB@
 
-if [ -f test_1.bbp ] && [ -f test_2.h5 ]
+if [ "$reportinglib" = "ON" ]
 then
-   #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
-   # for ascii files that will be using grep for instance.
-   nb_recorded=$(@reportinglib_LIB_DIR@/../usr/local/bin/somaDump test_1.bbp 1| wc -l)
-   nb_recorded_sonata=$(h5dump -d /report/data -y -O test_2.h5 | wc -l)
-   # 101 because a white space
-   if [ $nb_recorded -eq 100 ] && [ $nb_recorded_sonata -eq 101 ]; then
-     exit $OK
-   else
-     echo "[ERROR] The number of steps recorded doesn't match. Test failed!" >&2
+  if [ -f test_1.bbp ]
+  then
+     #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
+     # for ascii files that will be using grep for instance.
+     nb_recorded=$(@reportinglib_LIB_DIR@/../usr/local/bin/somaDump test_1.bbp 1| wc -l)
+     # 101 because a white space
+     if [ $nb_recorded -eq 100 ]; then
+       exit $OK
+     else
+       echo "[ERROR] The number of steps recorded doesn't match. Test failed!" >&2
+       exit $FAILED
+     fi
+  else
+     echo "[ERROR] reportinglib soma file doesn't exist. Test failed!" >&2
      exit $FAILED
-   fi
-else
-   echo "[ERROR] Soma report file doesn't exist. Test failed!" >&2
-   exit $FAILED
+  fi
 fi
 
+if [ "$sonata_reports" = "ON" ]
+then
+  if [ -f test_2.h5 ]
+  then
+     #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
+     # for ascii files that will be using grep for instance.
+     nb_recorded_sonata=$(h5dump -d /report/data -y -O test_2.h5 | wc -l)
+     # 101 because a white space
+     if [ $nb_recorded_sonata -eq 101 ]; then
+       exit $OK
+     else
+       echo "[ERROR] The number of steps recorded doesn't match. Test failed!" >&2
+       exit $FAILED
+     fi
+  else
+     echo "[ERROR] SONATA reports soma file doesn't exist. Test failed!" >&2
+     exit $FAILED
+  fi
+fi
