Error messages on integration tests

diff --git a/tests/integration/integration_test.sh.in b/tests/integration/integration_test.sh.in
--- a/tests/integration/integration_test.sh.in
+++ b/tests/integration/integration_test.sh.in
@@ -31,20 +31,20 @@ then
 
   if [ ! -f out_SONATA.dat ]
   then
-    echo "No SONATA output files. Test failed!"
+    echo "[ERROR] No SONATA output files. Test failed!" >&2
     exit 1
   fi
   diff -w out_SONATA.dat @CMAKE_CURRENT_SOURCE_DIR@/@SIM_NAME@/out.dat.ref > diff_SONATA.dat 2>&1
   if [ -s diff_SONATA.dat ]
   then
-    echo "SONATA Results are different, check the file diff_SONATA.dat. Test failed!"
+    echo "[ERROR] SONATA Results are different, check the file diff_SONATA.dat. Test failed!" >&2
     exit 1
   fi
 fi
 
 if [ ! -f out.dat ]
 then
-  echo "No output files. Test failed!"
+  echo "[ERROR] No output files. Test failed!" >&2
   exit 1
 fi
 
@@ -52,7 +52,7 @@ diff -w out.dat @CMAKE_CURRENT_SOURCE_DIR@/@SIM_NAME@/out.dat.ref > diff.dat 2>&
 
 if [ -s diff.dat ]
 then
-  echo "Results are different, check the file diff.dat. Test failed!"
+  echo "[ERROR] Results are different, check the file diff.dat. Test failed!" >&2
   exit 1
 else
   echo "Results are the same, test passed"
diff --git a/tests/integration/negative_integration_test.sh.in b/tests/integration/negative_integration_test.sh.in
--- a/tests/integration/negative_integration_test.sh.in
+++ b/tests/integration/negative_integration_test.sh.in
@@ -33,20 +33,20 @@ then
 
   if [ ! -f out_SONATA.dat ]
   then
-    echo "No SONATA output files. Test failed!"
+    echo "[ERROR] No SONATA output files. Test failed!" >&2
     exit 1
   fi
   diff -w out_SONATA.dat @CMAKE_CURRENT_SOURCE_DIR@/@SIM_NAME@/out.dat.ref > diff_SONATA.dat 2>&1
   if [ ! -s diff_SONATA.dat ]
   then
-    echo "Results are identical for SONATA file when they should not, check the file out_SONATA.dat. Test failed!"
+    echo "[ERROR] Results are identical for SONATA file when they should not, check the file out_SONATA.dat. Test failed!" >&2
     exit 1
   fi
 fi
 
 if [ ! -f out.dat ]
 then
-  echo "No output files. Test failed!"
+  echo "[ERROR] No output files. Test failed!" >&2
   exit 1
 fi
 
@@ -59,6 +59,6 @@ then
   rm -f *.dat
   exit 0
 else
-  echo "Results are identical when they should not, check the file diff.dat. Test failed!"
+  echo "[ERROR] Results are identical when they should not, check the file diff.dat. Test failed!" >&2
   exit 1
 fi
diff --git a/tests/integration/reportinglib/1.check.in b/tests/integration/reportinglib/1.check.in
--- a/tests/integration/reportinglib/1.check.in
+++ b/tests/integration/reportinglib/1.check.in
@@ -15,9 +15,11 @@ then
    if [ $nb_recorded -eq 100 ] && [ $nb_recorded_sonata -eq 101 ]; then
      exit $OK
    else
+     echo "[ERROR] The number of steps recorded doesn't match. Test failed!" >&2
      exit $FAILED
    fi
 else
+   echo "[ERROR] Soma report file doesn't exist. Test failed!" >&2
    exit $FAILED
 fi
 
