Support for SONATA reports (#225)
* Select report type at runtime (Bin, SONATA)
  - Revert SONATA_ENABLE cmake changes
  - Add ReportHandler class
* Refactor report module
  - Split nrnreport into different classes
  - Allow sonata reports to coexist with current reportinglib
  - Adapt integration tests for sonata reports
* Move sort_spikes after sonata_write_spikes
* Error messages on integration tests
* Fixed an issue where clang invoking the linker will always add mentioned libraries into the ELF
  header of the executable, this causes special-core to fail at load with libraries not found. By
  forcing the `--as-needed` flag, we reproduce the gcc behavior, which adds libraries only
  when needed and relies on the loader to recursively resolve libraries.
* Choose between reportinglib and sonata reports
  - If CORENRN_ENABLE_REPORTING variable is present, try to find a reporting library
   (reportinglib or sonata_reports) and allow its usage. Error if neither is found.
* Adapt tests to changes when choosing reporting library
* Add population name to the write_spikes
* Adapt report.conf file to CLI11
Co-authored-by: Tristan Carel <tristan.carel@gmail.com>
Co-authored-by: Blanco Alonso Jorge <jblanco@bbpv2.epfl.ch>
Co-authored-by: Omar Awile <omar.awile@epfl.ch>
Co-authored-by: Pramod Kumbhar <pramod.kumbhar@epfl.ch>

diff --git a/tests/integration/integration_test.sh.in b/tests/integration/integration_test.sh.in
--- a/tests/integration/integration_test.sh.in
+++ b/tests/integration/integration_test.sh.in
@@ -22,9 +22,29 @@ fi
 # diff outputed files with reference
 cd @CMAKE_CURRENT_BINARY_DIR@/@SIM_NAME@
 
+# We convert spikes to out.dat format
+reports=@ENABLE_SONATA_REPORTS@
+if [ "$reports" = "ON" ]
+then
+  data=$(@H5DUMP_EXECUTABLE@ -d /spikes/timestamps -d /spikes/node_ids -y -O out.h5 | tr "," "\n")
+  echo $data | awk '{n=NF/2; for (i=1;i<=n;i++) print $i "\t" $(n+i) }' >> out_SONATA.dat
+
+  if [ ! -f out_SONATA.dat ]
+  then
+    echo "[ERROR] No SONATA output files. Test failed!" >&2
+    exit 1
+  fi
+  diff -w out_SONATA.dat @CMAKE_CURRENT_SOURCE_DIR@/@SIM_NAME@/out.dat.ref > diff_SONATA.dat 2>&1
+  if [ -s diff_SONATA.dat ]
+  then
+    echo "[ERROR] SONATA Results are different, check the file diff_SONATA.dat. Test failed!" >&2
+    exit 1
+  fi
+fi
+
 if [ ! -f out.dat ]
 then
-  echo "No output files. Test failed!"
+  echo "[ERROR] No output files. Test failed!" >&2
   exit 1
 fi
 
@@ -32,7 +52,7 @@ diff -w out.dat @CMAKE_BINARY_DIR@/tests/integration/@SIM_NAME@/out.dat.ref > di
 
 if [ -s diff.dat ]
 then
-  echo "Results are different, check the file diff.dat. Test failed!"
+  echo "[ERROR] Results are different, check the file diff.dat. Test failed!" >&2
   exit 1
 else
   echo "Results are the same, test passed"
diff --git a/tests/integration/negative_integration_test.sh.in b/tests/integration/negative_integration_test.sh.in
--- a/tests/integration/negative_integration_test.sh.in
+++ b/tests/integration/negative_integration_test.sh.in
@@ -24,9 +24,29 @@ fi
 # diff outputed files with reference
 cd @CMAKE_CURRENT_BINARY_DIR@/@SIM_NAME@
 
+# We convert spikes to out.dat format
+reports=@ENABLE_SONATA_REPORTS@
+if [ "$reports" = "ON" ]
+then
+  data=$(@H5DUMP_EXECUTABLE@ -d /spikes/timestamps -d /spikes/node_ids -y -O spikes | tr "," "\n")
+  echo $data | awk '{n=NF/2; for (i=1;i<=n;i++) print $i "\t" $(n+i) }' >> out_SONATA.dat
+
+  if [ ! -f out_SONATA.dat ]
+  then
+    echo "[ERROR] No SONATA output files. Test failed!" >&2
+    exit 1
+  fi
+  diff -w out_SONATA.dat @CMAKE_CURRENT_SOURCE_DIR@/@SIM_NAME@/out.dat.ref > diff_SONATA.dat 2>&1
+  if [ ! -s diff_SONATA.dat ]
+  then
+    echo "[ERROR] Results are identical for SONATA file when they should not, check the file out_SONATA.dat. Test failed!" >&2
+    exit 1
+  fi
+fi
+
 if [ ! -f out.dat ]
 then
-  echo "No output files. Test failed!"
+  echo "[ERROR] No output files. Test failed!" >&2
   exit 1
 fi
 
@@ -39,6 +59,6 @@ then
   rm -f *.dat
   exit 0
 else
-  echo "Results are identical when they should not, check the file diff.dat. Test failed!"
+  echo "[ERROR] Results are identical when they should not, check the file diff.dat. Test failed!" >&2
   exit 1
 fi
diff --git a/tests/integration/reportinglib/1.check.in b/tests/integration/reportinglib/1.check.in
--- a/tests/integration/reportinglib/1.check.in
+++ b/tests/integration/reportinglib/1.check.in
@@ -4,18 +4,47 @@
 
 OK=0
 FAILED=1
+sonata_reports=@ENABLE_SONATA_REPORTS@
+bin_reports=@ENABLE_BIN_REPORTS@
 
-if [ -f test_1.bbp ] 
+if [ "$bin_reports" = "ON" ]
 then
-   #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
-   # for ascii files that will be using grep for instance.
-   nb_recorded=$(@reportinglib_somaDump@ test_1.bbp 1| wc -l)
-   if [ $nb_recorded -eq 100 ]; then
-     exit $OK
-   else
+  if [ -f test_1.bbp ]
+  then
+     #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
+     # for ascii files that will be using grep for instance.
+     nb_recorded=$(@reportinglib_somaDump@ test_1.bbp 1| wc -l)
+     # 101 because a white space
+     if [ $nb_recorded -eq 100 ]; then
+       exit $OK
+     else
+       echo "[ERROR] The number of steps recorded by ReportingLib doesn't match.
+             Found $nb_recorded, expected 100. Test failed!" >&2
+       exit $FAILED
+     fi
+  else
+     echo "[ERROR] Expected ReportingLib soma file 'test_1.bbp' is missing. Test failed!" >&2
      exit $FAILED
-   fi
-else
-   exit $FAILED
+  fi
 fi
 
+if [ "$sonata_reports" = "ON" ]
+then
+  if [ -f test_2.h5 ]
+  then
+     #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
+     # for ascii files that will be using grep for instance.
+     nb_recorded_sonata=$(@H5DUMP_EXECUTABLE@ -d /report/data -y -O test_2.h5 | wc -l)
+     # 101 because a white space
+     if [ $nb_recorded_sonata -eq 101 ]; then
+       exit $OK
+     else
+       echo "[ERROR] The number of steps recorded by SONATA doesn't match.
+            Found $nb_recorded, expected 101. Test failed!" >&2
+       exit $FAILED
+     fi
+  else
+     echo "[ERROR] Expected SONATA soma file 'test_2.h5' doesn't exist. Test failed!" >&2
+     exit $FAILED
+  fi
+fi
